"""Tests for the launch-script generators.

Two things are being guarded. First, the scripts must be *valid shell* —
they are generated by string assembly, so every test that produces one runs
``bash -n`` over it. Second, nothing in this layer may execute anything:
codt_tools writes a script and the user launches it, which is what keeps the
package free of any knowledge of accounts, partitions or clusters.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from codt_tools.case import Case
from codt_tools.run import Run, launcher, write_local, write_slurm_array


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check_syntax(script: Path) -> None:
    """Fail the test if bash cannot parse the generated script."""
    proc = subprocess.run(
        ["bash", "-n", str(script)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, (
        f"generated script is not valid bash:\n{proc.stderr}"
    )


@pytest.fixture
def runs(tmp_path: Path) -> list[Run]:
    """Four staged runs sharing one executable."""
    base = Case()
    base.set(simulation_name="sweep")
    cases = base.sweep({"params.tref": [20.0, 21.0, 22.0, 23.0]})
    made = Run.for_cases(cases, tmp_path / "bin" / "CODT", tmp_path / "ens")
    for one in made:
        one.stage()
    return made


# ---------------------------------------------------------------------------
# write_local
# ---------------------------------------------------------------------------

class TestWriteLocal:
    """A background-parallel launcher for this machine."""

    def test_is_valid_bash(self, runs: list[Run], tmp_path: Path) -> None:
        _check_syntax(write_local(runs, tmp_path / "run_all.sh"))

    def test_returns_an_executable_script(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        path = write_local(runs, tmp_path / "run_all.sh")

        assert path.is_file()
        assert path.stat().st_mode & 0o111

    def test_lists_every_run_by_absolute_path(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_local(runs, tmp_path / "run_all.sh").read_text()

        for one in runs:
            assert str(one.workdir) in text
            assert one.workdir.is_absolute()

    def test_has_the_done_guard(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        """Re-running the script must resume, not redo."""
        text = write_local(runs, tmp_path / "run_all.sh").read_text()

        assert 'compgen -G "$RUN_DIR/output/*_DONE"' in text

    def test_invokes_an_absolute_namelist_path(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_local(runs, tmp_path / "run_all.sh").read_text()

        assert '"$EXE" "$RUN_DIR/inputs/params.nml"' in text

    @pytest.mark.parametrize("jobs", [1, 3, 16])
    def test_jobs_caps_concurrency(
        self, runs: list[Run], tmp_path: Path, jobs: int
    ) -> None:
        path = write_local(runs, tmp_path / "run_all.sh", jobs=jobs)
        text = path.read_text()

        assert f"JOBS={jobs}" in text
        assert "while (( $(jobs -rp | wc -l) >= JOBS )); do wait -n; done" in text
        _check_syntax(path)

    def test_rejects_a_bad_job_count(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        with pytest.raises(ValueError, match="at least 1"):
            write_local(runs, tmp_path / "run_all.sh", jobs=0)

    def test_timing_file_defaults_beside_the_script(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_local(runs, tmp_path / "sub" / "run_all.sh").read_text()

        assert str(tmp_path / "sub" / "timing.txt") in text

    def test_runs_serially_when_jobs_is_one(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        """A serial script is still the same script, throttled to one."""
        path = write_local(runs, tmp_path / "run_all.sh", jobs=1)

        assert "JOBS=1" in path.read_text()
        _check_syntax(path)


# ---------------------------------------------------------------------------
# write_slurm_array
# ---------------------------------------------------------------------------

class TestWriteSlurmArray:
    """A job-array template plus the manifest its tasks read."""

    def test_is_valid_bash(self, runs: list[Run], tmp_path: Path) -> None:
        _check_syntax(write_slurm_array(runs, tmp_path / "array.sh"))

    def test_placeholders_when_directives_are_omitted(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        """An obvious blank beats a wrong default: SLURM refuses the script
        until these are filled in."""
        text = write_slurm_array(runs, tmp_path / "array.sh").read_text()

        assert "#SBATCH --account=<ACCOUNT>" in text
        assert "#SBATCH --partition=<PARTITION>" in text
        assert "#SBATCH --time=<TIME>" in text

    def test_directives_are_filled_when_given(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        path = write_slurm_array(
            runs,
            tmp_path / "array.sh",
            account="krueger",
            partition="notchpeak-freecycle",
            qos="notchpeak-freecycle",
            constraint="rom",
            time="12:00:00",
            mem="8G",
        )
        text = path.read_text()

        assert "#SBATCH --account=krueger" in text
        assert "#SBATCH --partition=notchpeak-freecycle" in text
        assert "#SBATCH --qos=notchpeak-freecycle" in text
        assert "#SBATCH --constraint=rom" in text
        assert "#SBATCH --time=12:00:00" in text
        assert "#SBATCH --mem=8G" in text
        assert "<" not in text.split("\n\n")[0]

    def test_optional_directives_are_absent_when_unset(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_slurm_array(runs, tmp_path / "array.sh").read_text()

        assert "--qos" not in text
        assert "--constraint" not in text
        assert "--mem" not in text

    def test_extra_directives_become_dashed_options(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_slurm_array(
            runs, tmp_path / "array.sh", mail_type="END"
        ).read_text()

        assert "#SBATCH --mail-type=END" in text

    @pytest.mark.parametrize(
        "runs_per_task, n_tasks, ntasks",
        [(1, 4, 1), (2, 2, 2), (3, 2, 3), (4, 1, 4), (8, 1, 4)],
    )
    def test_manifest_lines_match_runs_per_task(
        self,
        runs: list[Run],
        tmp_path: Path,
        runs_per_task: int,
        n_tasks: int,
        ntasks: int,
    ) -> None:
        path = write_slurm_array(
            runs, tmp_path / "array.sh", runs_per_task=runs_per_task
        )
        manifest = tmp_path / "array_runs.txt"
        lines = manifest.read_text().strip().splitlines()

        assert len(lines) == n_tasks
        assert f"#SBATCH --array=0-{n_tasks - 1}" in path.read_text()
        assert f"#SBATCH --ntasks={ntasks}" in path.read_text()

    def test_manifest_holds_every_run_once(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        write_slurm_array(runs, tmp_path / "array.sh", runs_per_task=3)
        listed = (tmp_path / "array_runs.txt").read_text().split()

        assert sorted(listed) == sorted(str(r.workdir) for r in runs)
        assert all(Path(d).is_absolute() for d in listed)

    def test_task_reads_its_own_manifest_line(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_slurm_array(runs, tmp_path / "array.sh").read_text()

        assert str(tmp_path / "array_runs.txt") in text
        assert 'read -ra RUNS <<< "${TASKS[$SLURM_ARRAY_TASK_ID]}"' in text

    def test_throttle_renders_on_the_array_spec(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_slurm_array(
            runs, tmp_path / "array.sh", array_throttle=2
        ).read_text()

        assert "#SBATCH --array=0-3%2" in text

    def test_requeue_is_on_by_default(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        """Requeue is only safe because of the _DONE guard; the two ship
        together."""
        text = write_slurm_array(runs, tmp_path / "array.sh").read_text()

        assert "#SBATCH --requeue" in text
        assert 'compgen -G "$RUN_DIR/output/*_DONE"' in text

    def test_requeue_can_be_turned_off(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_slurm_array(
            runs, tmp_path / "array.sh", requeue=False
        ).read_text()

        assert "--requeue" not in text

    def test_module_line_is_emitted(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        """The Rome build has no libgfortran RPATH and cannot start
        without this."""
        path = write_slurm_array(
            runs, tmp_path / "array.sh", module="gcc/11.2.0"
        )

        assert "module load gcc/11.2.0" in path.read_text()
        _check_syntax(path)

    def test_job_name_defaults_to_the_script_stem(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        text = write_slurm_array(runs, tmp_path / "ens42.sh").read_text()

        assert "#SBATCH --job-name=ens42" in text
        assert "#SBATCH --output=" in text

    def test_custom_manifest_path(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        write_slurm_array(
            runs, tmp_path / "array.sh", manifest=tmp_path / "custom.txt"
        )

        assert (tmp_path / "custom.txt").is_file()

    def test_rejects_a_bad_task_size(
        self, runs: list[Run], tmp_path: Path
    ) -> None:
        with pytest.raises(ValueError, match="at least 1"):
            write_slurm_array(runs, tmp_path / "array.sh", runs_per_task=0)


# ---------------------------------------------------------------------------
# Shared refusals
# ---------------------------------------------------------------------------

class TestRefusals:
    """Cases where generating a script would produce a wrong one."""

    @pytest.mark.parametrize("writer", [write_local, write_slurm_array])
    def test_empty_batch_raises(self, writer, tmp_path: Path) -> None:
        with pytest.raises(ValueError, match="No runs"):
            writer([], tmp_path / "script.sh")

    @pytest.mark.parametrize("writer", [write_local, write_slurm_array])
    def test_mixed_executables_raise(self, writer, tmp_path: Path) -> None:
        """A script names one $EXE, so a mixed batch would silently run
        half of itself with the wrong binary."""
        case = Case()
        case.set(simulation_name="s")
        mixed = [
            Run(case, tmp_path / "CODT_a", tmp_path / "a"),
            Run(case, tmp_path / "CODT_b", tmp_path / "b"),
        ]

        with pytest.raises(ValueError, match="different executables"):
            writer(mixed, tmp_path / "script.sh")


# ---------------------------------------------------------------------------
# The architectural guarantee
# ---------------------------------------------------------------------------

class TestNothingIsSubmitted:
    """This layer generates text. It does not run schedulers."""

    def test_launcher_imports_no_way_to_execute_anything(self) -> None:
        """The module may *say* sbatch — it writes sbatch scripts — but it
        must not import the machinery to run one."""
        source = Path(launcher.__file__).read_text()

        for forbidden in ("import subprocess", "import os", "Popen",
                          "os.system", "check_call", "check_output"):
            assert forbidden not in source, (
                f"launcher.py should not be able to execute anything, "
                f"found: {forbidden}"
            )

    def test_generating_a_script_touches_no_scheduler(
        self, runs: list[Run], tmp_path: Path, monkeypatch
    ) -> None:
        def _forbidden(*args, **kwargs):
            raise AssertionError(f"launcher executed something: {args}")

        monkeypatch.setattr(subprocess, "run", _forbidden)
        monkeypatch.setattr(subprocess, "Popen", _forbidden)

        write_local(runs, tmp_path / "run_all.sh")
        write_slurm_array(runs, tmp_path / "array.sh")
